#! /usr/bin/env python

from fusion_utils.run import *
import argparse

parser = argparse.ArgumentParser(prog = "fusion_comp")

parser.add_argument("--version", action = "version", version = "fusion_comp-0.1.0")

parser.add_argument("fusion1", metavar = "fusion1.txt", default = None, type = str,
                    help = "the path to the 1st fusion")

parser.add_argument("type1", choices=["fusionfusion", "genomonSV", "star_fusion", "genomon_fusion"], default = "fusionfusion",
                    help = "the type of the 1st fusion")

parser.add_argument("fusion2", metavar = "fusion2.txt", default = None, type = str,
                    help = "the path to the 2nd fusion")

parser.add_argument("type2", choices=["fusionfusion", "genomonSV", "star_fusion", "genomon_fusion"], default = "fusionfusion",
                    help = "the type of the 2nd fusion")

parser.add_argument("output", metavar = "output.txt", default = None, type = str,
                    help = "the path to the output")

parser.add_argument("bedtools_path", metavar = "bedtools_path", type = str, 
                    help = "the path to the bedtools")

args = parser.parse_args()

main(args)

